# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reporter_or_agent',
        ),
    ]
